-- ==========================================
-- SUPABASE DATABASE SCHEMA FOR PORTFOLIO
-- Execute this SQL script in Supabase SQL Editor
-- ==========================================

-- 1. Profile Table
CREATE TABLE IF NOT EXISTS public.profile (
    id BIGINT PRIMARY KEY DEFAULT 1,
    name TEXT,
    subtitles JSONB DEFAULT '[]'::jsonb,
    subtitles_id JSONB DEFAULT '[]'::jsonb,
    subtitles_en JSONB DEFAULT '[]'::jsonb,
    bio TEXT,
    bio_id TEXT,
    bio_en TEXT,
    profile_image TEXT,
    profile_image_1 TEXT,
    profile_image_2 TEXT,
    profile_image_3 TEXT,
    profile_images JSONB DEFAULT '[]'::jsonb,
    github TEXT,
    linkedin TEXT,
    instagram TEXT,
    email TEXT,
    mission TEXT,
    mission_id TEXT,
    mission_en TEXT,
    years_exp TEXT,
    projects_count TEXT,
    career_goals TEXT,
    career_goals_id TEXT,
    career_goals_en TEXT,
    education JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS & Policies for profile
ALTER TABLE public.profile ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on profile" ON public.profile;
DROP POLICY IF EXISTS "Allow public write access on profile" ON public.profile;
CREATE POLICY "Allow public read access on profile" ON public.profile FOR SELECT USING (true);
CREATE POLICY "Allow public write access on profile" ON public.profile FOR ALL USING (true) WITH CHECK (true);

-- 2. Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    description TEXT,
    image_url TEXT,
    tech_stack JSONB DEFAULT '[]'::jsonb,
    github_link TEXT,
    live_link TEXT,
    category TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on projects" ON public.projects;
DROP POLICY IF EXISTS "Allow public write access on projects" ON public.projects;
CREATE POLICY "Allow public read access on projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Allow public write access on projects" ON public.projects FOR ALL USING (true) WITH CHECK (true);

-- 3. Skills Table
CREATE TABLE IF NOT EXISTS public.skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    category TEXT,
    level INTEGER DEFAULT 80,
    icon TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on skills" ON public.skills;
DROP POLICY IF EXISTS "Allow public write access on skills" ON public.skills;
CREATE POLICY "Allow public read access on skills" ON public.skills FOR SELECT USING (true);
CREATE POLICY "Allow public write access on skills" ON public.skills FOR ALL USING (true) WITH CHECK (true);

-- 4. Experiences Table
CREATE TABLE IF NOT EXISTS public.experiences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    company TEXT,
    location TEXT,
    start_date TEXT,
    end_date TEXT,
    description TEXT,
    highlights JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.experiences ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on experiences" ON public.experiences;
DROP POLICY IF EXISTS "Allow public write access on experiences" ON public.experiences;
CREATE POLICY "Allow public read access on experiences" ON public.experiences FOR SELECT USING (true);
CREATE POLICY "Allow public write access on experiences" ON public.experiences FOR ALL USING (true) WITH CHECK (true);

-- 5. Certificates Table
CREATE TABLE IF NOT EXISTS public.certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    issuer TEXT,
    date TEXT,
    credential_id TEXT,
    credential_url TEXT,
    type TEXT,
    issuer_logo TEXT,
    pdf_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access on certificates" ON public.certificates;
DROP POLICY IF EXISTS "Allow public write access on certificates" ON public.certificates;
CREATE POLICY "Allow public read access on certificates" ON public.certificates FOR SELECT USING (true);
CREATE POLICY "Allow public write access on certificates" ON public.certificates FOR ALL USING (true) WITH CHECK (true);
